name: Build tests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    # paths:
    #   - "**.sh"
    #   - "**.py"
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: setup
    - run: pip install black==22.8.0

    - name: black linter
      run: black --diff --check ./
  
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: some tests
        run: |
          echo "running tests"
