name: Branch tests

on: [push, workflow_dispatch]

jobs:
  branch_lint:
    name: Linting tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11.2

      - name: Setup build environment
        run: |
          python --version
          ./bash/setup_build_env.sh

      - name: Run truck linter
        uses: trunk-io/trunk-action@v1
        # with:
        #   check-mode: all

  branch_unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: Setup build environment
        run: |
          python --version
          ./bash/setup_build_env.sh

      - name: Run python tests
        run: |
          python3 -m pytest

  branch_dev_container_tests:
    name: Dev container tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "CI environment variable is $CI"
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pip list

  branch_build_tests:
    name: Build tests
    uses: ./.github/workflows/build.yml
    with:
      logging_level: DEBUG
    secrets: inherit
