name: Branch tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  branch_lint:
    name: Branch lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: setup
        run: pip install black==22.8.0

      - name: black linter
        run: black --diff --check ./

  branch_tests:
    name: Branch tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: some tests
        run: |
          echo "running tests"
