name: Branch tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  branch_lint:
    name: Linting tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"

      - name: setup
        run: pip install black==22.8.0

      - name: black linter
        run: black --diff --check ./

  some_unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: some tests
        run: |
          echo "running tests"

  branch_tests_with_devcontainer:
    runs-on: ubuntu-latest
    container: nycplanning/library:ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - name: setup python
      #   uses: actions/setup-python@v4.5.0
      #   with:
      #     python-version: "3.9"

      # - name: setup poetry image
      #   uses: abatilo/actions-poetry@v2
      #   with:
      #     poetry-version: "1.3.2"

      - name: View poetry --help
        run: poetry --help

      # - name: start containers
      #   run: docker-compose --file ".devcontainer/docker-compose.yml" up --detach --build

      # - name: check running containers
      #   run: |
      #     docker ps --all

      - name: check path
        run: |
          echo "$PATH"

      - name: confirm python packages (pip)
        run: |
          pip list

      - name: confirm python packages (poetry)
        run: |
          poetry show
