name: Branch tests

on:
  push:
  workflow_dispatch:

jobs:
  branch_lint:
    name: Linting tests (python files)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.1"

      - name: setup
        run: pip install black==22.8.0

      - name: black linter
        run: black --diff --check ./

  branch_unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: some tests [PLACEHOLDER]
        run: |
          echo "running tests ..."
          # TODO add pytest tests

  branch_devcontainer_tests:
    name: Devcontainer tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "CI envar is $CI"
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pip list

  branch_build_tests:
    name: Build tests
    uses: ./.github/workflows/build.yml
    with:
      logging_level: "DEBUG"
    secrets: inherit
