name: Branch tests

on:
  push:
  workflow_dispatch:

jobs:
  branch_lint:
    name: Linting tests (python files)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: Setup build environment
        run: |
          python --version
          ./bash/setup_build_env.sh

      - name: Run black linter
        run: black --diff --check ./

  branch_unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: some tests [PLACEHOLDER]
        run: |
          echo "running tests ..."
          # TODO add pytest tests

  branch_dev_container_tests:
    name: Dev container tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "CI environment variable is $CI"
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pip list

  branch_build_tests:
    name: Build tests
    uses: ./.github/workflows/build.yml
    with:
      logging_level: "DEBUG"
    secrets: inherit
