name: Branch tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  branch_lint:
    name: Linting tests (python files)
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.1"

      - name: setup
        run: pip install black==22.8.0

      - name: black linter
        run: black --diff --check ./

  branch_unit_tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: some tests [PLACEHOLDER]
        run: |
          echo "running tests ..."
